### ISSUE TITLE
Edge Browser Issue

### ISSUE THREAD

**Issue by DeviKarthi** [speti43/DobozMeetup#1]
Hi Everyone., 
    When I use [ng4-file-upload] Edge browser the  file upload popup does not closed, Can some one help me to fix this issue.
Thank you.

**Comment by speti43** [comment]
Hi,

Do you have any js error, or some more details?

Peter

**Comment by speti43** [comment]
I think its polyfill issue:

look in your polyfill.ts (app/polyfill.ts), uncomment these lines, or jus
paste it:
/** IE9, IE10 and IE11 requires all of the following polyfills. **/

import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';



/** Evergreen browsers require these. **/
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';


/***************************************************************************************************
* Zone JS is required by Angular itself.
*/
import 'zone.js/dist/zone'; // Included with Angular CLI.

**Comment by DeviKarthi** [comment]
When i click browse button the popup opened, after that i can not able to do inspect element or view source in Edge browser. Then i tried click to open or cancel the popup automatically rerender again and again.

**Comment by speti43** [comment]
Strange, I've just tried in my project in edge browser, after polyfill fix, it works for me perfectly.

**Comment by DeviKarthi** [comment]
@speti43  I checked into my **polyfills.ts**,  the above you mentioned lines are already there.

**Comment by speti43** [comment]
Can you check, if a simple html fileupload works the same way? Just put
this on your page:
  <input name="myFile" type="file">

**Comment by DeviKarthi** [comment]
@speti43  I checked into the latest Edge browser it's working fine with my existing code (ng4-file-upload) itself. Thank you.

**Comment by speti43** [comment]
That's good news! You're welcome!
