### ISSUE TITLE
Angular 4 File Uploader Control Clear Issue

### ISSUE THREAD

**Issue by DeviKarthi** [speti43/DobozMeetup#2]
@speti43 , i have to clear the text(2 files has been selected..) inside control.

![image](https://user-images.githubusercontent.com/32258563/30846986-6d040f82-a2b7-11e7-9b3e-932bae9c2e7d.png)

**Comment by speti43** [comment]
Do you need a delete button, which removes the file, and clears the text as well?

**Comment by DeviKarthi** [comment]
@speti43, No, When they choose invalid file format or they choose multiple files at a time i need to clear the above text value.

**Comment by speti43** [comment]
If you set these properties correctly, they cannot choose multiple file, or wrong file format. E.g.:
<file-uploader [allowMultiple]="false" [fileType]="'application/pdf'"

You can use these mime types for correct file format filter:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types

**Comment by DeviKarthi** [comment]
@speti43, am using like the below, here i need to allow multiple file format so i validated within the changeevent.
<file-uploader name="fileNameUpload" class="row form-group" [allowMultiple]="false" [fileType]="'application/*'" (onSelection)="fileuploaderFileChange($event)"
                                [required]="false"></file-uploader>
But when i click browse button after open popup i can able to choose multiple files with the help of ctrl key.

**Comment by speti43** [comment]
I've just made the bugfix. Get the latest version:
npm i ng4-file-upload@latest --save

Use this way (False with capital F) and you can specify multiple types:
<file-uploader [allowMultiple]="False" [fileType]="'application/pdf;application/msword;application/vnd.openxmlformats-officedocument.wordprocessingml.document'"

**Comment by DeviKarthi** [comment]
@speti43, Thank you.
