### ISSUE TITLE
ENOENT After npm install

### ISSUE THREAD

**Issue by richie50** [speti43/DobozMeetup#3]
Error: Module build failed: Error: ENOENT: no such file or directory, open 'C:\Users\****\****\****\*****\ng4-file-upload\file-uploader.module.js.map'

Angular CLI: 1.5.5
Node: 8.4.0
OS: win32 x64
Angular: 5.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

angular/cli: 1.5.5
angular-devkit/build-optimizer: 0.0.36
angular-devkit/core: 0.0.22
angular-devkit/schematics: 0.0.42
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.8.5
schematics/angular: 0.1.11
schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.8.1

**Comment by speti43** [comment]
Try now.
I've just pushed the fix.
Note: I've upgraded to Angular5.
Try a clean npm install, build.
